name: npm-patch-string
inputs:
  path:
    description: path from where to run the actions
    type: string
    required: false
    default: ${{ github.workspace }}
  spec:
    description: package spec (path to package.json)
    type: string
    required: false
    default: package.json
  element:
    description: name of string element to replace (including '.')
    type: string
    required: true
  value:
    description: value to replace element with
    type: string
    required: true
runs:
  using: composite
  steps:
  - name: Before patch
    shell: bash
    run: |-
      pushd ${{ inputs.path }}
      cat ${{ inputs.spec }}
      popd
  - name: Patch
    id: patch
    shell: bash
    run: |-
      pushd ${{ inputs.path }}
      contents="$(jq --arg v '${{ inputs.value }}' '${{ inputs.element }} = $v' ${{ inputs.spec }})"
      echo -E "${contents}" > ${{ inputs.spec }}
      popd
  - name: After patch
    shell: bash
    run: |-
      pushd ${{ inputs.path }}
      cat ${{ inputs.spec }}
      popd
