name: check-if-merge
inputs:
  path:
    description: path from where to run the actions
    type: string
    required: false
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
  - name: Check if triggered by merge commit
    shell: bash
    run: |-
      pushd ${{ inputs.path }}
      head_commit=$(git --no-pager log --pretty=%s -n 1 HEAD)
      last_merge=$(git --no-pager log --pretty=%s --merges -n 1)
      echo "HEAD commit: $head_commit"
      echo "Last merge: $last_merge"

      if [[ "$last_merge" == "$head_commit" ]]; then
        echo "Found merge commit"
      else
        echo "No merge commit. Suspending job here."
        gh run cancel ${{ github.run_id }}
      fi
      popd
