name: push-tag
inputs:
  repositoryUrl:
    description: URL of git repo to push to (name or URL, e.g 'https://secrets.GITHUB_TOKEN@github.com/owner/repo.git')
    required: true
  baseBranch:
    description: repo base branch to push to
    required: false
    default: main
  mergeBranch:
    description: repo branch to push to
    required: false
    default: main
runs:
  using: composite
  steps:
  - name: Push tag
    shell: bash
    run: |-
      git push -u --verbose --tags ${{ inputs.repositoryUrl }}
      git push -u --verbose --follow-tags ${{ inputs.repositoryUrl }} ${{ inputs.mergeBranch }}
  - name: Create Pull Request
    shell: bash
    run: |-
      j="$(gh pr status --json title,number,headRefName,body)"
      num=$(jq -r .currentBranch.number <<< $j)
      title="$(jq -r .currentBranch.title <<< $j) ($(jq -r .currentBranch.headRefName <<< $j)) [#$num]"
      gh pr create --base ${{ inputs.baseBranch }} --fill
      gh pr edit -t "${title}"
  - name: Create Pull Request
    shell: bash
    run: |-
      gh pr merge --rebase --delete-branch
