name: push-tag
inputs:
  repositoryUrl:
    description: URL of git repo to push to (name or URL, e.g 'https://secrets.GITHUB_TOKEN@github.com/owner/repo.git')
    required: true
  branch:
    description: repo branch to push to
    required: false
    default: main
runs:
  using: composite
  steps:
  - name: Push tag
    shell: bash
    env:
      GH_TOKEN: ${{ github.token }}
    run: |-
      git push -u --force --verbose ${{ inputs.repositoryUrl }} ${{ inputs.branch }}
      git push -u --force --verbose --follow-tags ${{ inputs.repositoryUrl }} ${{ inputs.branch }}
