name: push-tag
inputs:
  path:
    description: path from where to run the actions
    type: string
    required: false
    default: ${{ github.workspace }}
  remote:
    description: URL of git repo to push to (name or URL, e.g 'https://secrets.GITHUB_TOKEN@github.com/owner/repo.git')
    required: true
  branch:
    description: repo branch to push to
    required: false
    default: main
  dry-run:
    description: whether to perform a dry-run
    type: boolean
    default: false
runs:
  using: composite
  steps:
  - name: Push tag (dry run)
    if: ${{ inputs.dry-run == true }}
    shell: pwsh
    env:
      GH_TOKEN: ${{ github.token }}
    run: |-
      Push-Location ${{ inputs.path }}
      git push --force-with-lease --verbose --dry-run ${{ inputs.remote }} ${{ inputs.branch }}
      git push --force-with-lease --verbose --dry-run --follow-tags ${{ inputs.remote }} ${{ inputs.branch }}
      git push --force-with-lease --verbose --dry-run --tags ${{ inputs.remote }}
      Pop-Location
  - name: Push tag (for real)
    if: ${{ inputs.dry-run == false }}
    shell: pwsh
    env:
      GH_TOKEN: ${{ github.token }}
    run: |-
      Push-Location ${{ inputs.path }}
      git push --force-with-lease --verbose           ${{ inputs.remote }} ${{ inputs.branch }}
      git push --force-with-lease --verbose           --follow-tags ${{ inputs.remote }} ${{ inputs.branch }}
      git push --force-with-lease --verbose           --tags ${{ inputs.remote }}
      Pop-Location
