name: install-prerequisites
runs:
  using: composite
  steps:
  - name: Install prequisites
    shell: bash
    run: |-
      sudo apt-get update -y -qq
      sudo apt-get install -y fd-find ripgrep curl wget sed moreutils jq apt-utils zsh snapd
      sudo snap install xq
  - name: Verify installation
    shell: bash
    run: |-
      which fdfind
      which rg
      which curl
      which wget
      which sed
      which jq
      which xq
