name: check-if-tag
inputs:
  path:
    description: path from where to run the actions
    type: string
    required: false
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
  - name: Check if triggered by tag commit
    shell: bash
    run: |-
      pushd ${{ inputs.path }}
      head_commit=$(git --no-pager log --pretty=%s -n 1 HEAD)
      last_tag=$(git --no-pager log --pretty=%s --tags -n 1)
      echo "HEAD commit: $head_commit"
      echo "Last tag: $last_tag"

      if [[ "$last_tag" == "$head_commit" ]]; then
        echo "Found tag commit"
      else
        echo "No tag commit. Suspending job here."
        gh run cancel ${{ github.run_id }}
      fi
      popd
