name: checkout-repo
inputs:
  repositoryUrl:
    required: true
  repositoryPath:
    required: false
    default: ./repo
  repositoryBranch:
    required: false
    default: main
runs:
  using: composite
  steps:
  - name: Clone ${{ inputs.repositoryUrl }} as ${{ inputs.repositoryPath }}
    shell: bash
    run: |
      if [[ ! -d {{ inputs.repositoryPath }} ]]; then
        git clone -b ${{ inputs.repositoryBranch }} ${{ inputs.repositoryUrl }} ${{ inputs.repositoryPath }}
      else
        git -C ${{ inputs.repositoryPath }} fetch
        git -C ${{ inputs.repositoryPath }} reset --hard origin/${{ inputs.repositoryBranch }}
      fi
      git -C ${{ inputs.repositoryPath }} fetch --tags
