name: checkout-repo
inputs:
  repositoryUrl:
    required: true
  repositoryPath:
    required: false
    default: ./repo
  repositoryBranch:
    required: false
    default: main
runs:
  using: composite
  steps:
  - name: Clone ${{ inputs.repositoryUrl }} as ${{ inputs.repositoryPath }}
    uses: kagekirin/gha-utils/.github/actions/git-checkout-tags@main
    with:
      repository: ${{ inputs.repositoryUrl }}
      path: ${{ inputs.repositoryPath }}
      ref: ${{ inputs.repositoryBranch }}
