name: actions/tag-generate
inputs:
  version:
    description: product version/tag
    required: true
  add-revcount:
    description: whether to include revcount
    required: false
    default: false
  prerelease:
    description: version '-prerelease.num' part
    required: false
    default: ''
  buildmeta:
    description: version '+buildmeta.text' part
    required: false
    default: ''
outputs:
  version:
    description: updated tag/version
    value: ${{ steps.generate-tag.outputs.version }}
runs:
  using: composite
  steps:
  - id: get-revcount
    shell: pwsh
    run: |-
      $revcount = @(git rev-list --tags --count)
      echo "revcount=$revcount"
      echo "revcount=$revcount" >> $Env:GITHUB_OUTPUT
  - shell: pwsh
    run: |-
      echo "revcount=${{ steps.get-revcount.outputs.revcount }}"
  - id: generate-tag
    shell: pwsh
    run: |-
      $prerelease = "${{ inputs.prerelease }}"
      $buildmeta = "${{ inputs.buildmeta }}"
      $version = "${{ inputs.version }}"

      if (! [string]::IsNullOrEmpty($prerelease))
      {
        $version = "$version-$prerelease"
      }

      if ($${{ inputs.add-revcount }})
      {
        $version = "$version.${{ steps.get-revcount.outputs.revcount }}"
      }

      if (! [string]::IsNullOrEmpty($buildmeta))
      {
        $version = "$version+$buildmeta"
      }

      echo "version=$version"
      echo "version=$version" >> $Env:GITHUB_OUTPUT
  - shell: pwsh
    run: |-
      echo "generated version: ${{ steps.generate-tag.outputs.version }}"
